// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../hoshidicts.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `as_ptr`, `cstring`, `len`, `new`, `take_string`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `CStringList`, `HoshiBytes`, `LookupResponse`, `OperationResult`, `StylesResponse`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `drop`, `fmt`, `fmt`, `fmt`

Future<HoshiImportResult> importDictionary({
  required String zipPath,
  required String outputDir,
  required bool lowRam,
}) => RustLib.instance.api.crateApiHoshidictsNativeImportDictionary(
  zipPath: zipPath,
  outputDir: outputDir,
  lowRam: lowRam,
);

Future<HoshiLookupSession> createLookupSession() =>
    RustLib.instance.api.crateApiHoshidictsNativeCreateLookupSession();

Future<void> rebuildQuery({
  required HoshiLookupSession session,
  required List<String> termPaths,
  required List<String> freqPaths,
  required List<String> pitchPaths,
}) => RustLib.instance.api.crateApiHoshidictsNativeRebuildQuery(
  session: session,
  termPaths: termPaths,
  freqPaths: freqPaths,
  pitchPaths: pitchPaths,
);

Future<List<HoshiLookupResult>> lookup({
  required HoshiLookupSession session,
  required String text,
  required int maxResults,
  required BigInt scanLength,
}) => RustLib.instance.api.crateApiHoshidictsNativeLookup(
  session: session,
  text: text,
  maxResults: maxResults,
  scanLength: scanLength,
);

Future<List<HoshiDictionaryStyle>> getStyles({
  required HoshiLookupSession session,
}) => RustLib.instance.api.crateApiHoshidictsNativeGetStyles(session: session);

Future<Uint8List?> getMediaFile({
  required HoshiLookupSession session,
  required String dictName,
  required String mediaPath,
}) => RustLib.instance.api.crateApiHoshidictsNativeGetMediaFile(
  session: session,
  dictName: dictName,
  mediaPath: mediaPath,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<HoshiLookupSession>>
abstract class HoshiLookupSession implements RustOpaqueInterface {}
