// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `declared_encoding`, `decode_text_resource`, `decode_utf16`, `epub_content_is_renderable`, `epub_paths_match`, `extract_resources_from_archive`, `extract_resources_with_content_from_bytes`, `extract_resources_with_content`, `find_chapter_name_from_toc`, `is_epub_reader_auxiliary_asset`, `normalize_epub_path`, `parse_epub_with_doc`, `percent_decode_path`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`

Future<EpubNovel> parseEpubFromPath({
  required String epubPath,
  required bool fullData,
}) => RustLib.instance.api.crateApiEpubParseEpubFromPath(
  epubPath: epubPath,
  fullData: fullData,
);

Future<EpubNovel> parseEpubFromBytes({
  required List<int> epubBytes,
  required bool fullData,
}) => RustLib.instance.api.crateApiEpubParseEpubFromBytes(
  epubBytes: epubBytes,
  fullData: fullData,
);

/// Get chapter content from EPUB by path
Future<String> getChapterContent({
  required String epubPath,
  required String chapterPath,
}) => RustLib.instance.api.crateApiEpubGetChapterContent(
  epubPath: epubPath,
  chapterPath: chapterPath,
);

class EpubChapter {
  /// Logical section name inherited from the nearest preceding EPUB TOC
  /// entry. Raw spine fragments remain separate for reliable rendering.
  final String name;
  final String content;
  final String path;

  /// Canonical path inside the EPUB archive. This is intentionally kept
  /// alongside [path] so existing records remain readable while the reader
  /// can resolve images, footnotes, and cross-chapter links correctly.
  final String href;

  /// Stable position in the original OPF spine.
  final int spineIndex;

  /// Whether this item participates in the OPF linear reading order.
  final bool isLinear;

  /// Whether this spine item should appear in the user-facing chapter list.
  /// Non-navigation fragments are still kept for seamless reader paging.
  final bool isNavigationEntry;

  const EpubChapter({
    required this.name,
    required this.content,
    required this.path,
    required this.href,
    required this.spineIndex,
    this.isLinear = true,
    required this.isNavigationEntry,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      content.hashCode ^
      path.hashCode ^
      href.hashCode ^
      spineIndex.hashCode ^
      isLinear.hashCode ^
      isNavigationEntry.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EpubChapter &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          content == other.content &&
          path == other.path &&
          href == other.href &&
          spineIndex == other.spineIndex &&
          isLinear == other.isLinear &&
          isNavigationEntry == other.isNavigationEntry;
}

class EpubNovel {
  final String name;
  final Uint8List? cover;
  final String? summary;
  final String? author;
  final String? artist;
  final List<EpubChapter> chapters;
  final List<EpubResource> images;
  final List<EpubResource> stylesheets;

  const EpubNovel({
    required this.name,
    this.cover,
    this.summary,
    this.author,
    this.artist,
    required this.chapters,
    required this.images,
    required this.stylesheets,
  });

  @override
  int get hashCode =>
      name.hashCode ^
      cover.hashCode ^
      summary.hashCode ^
      author.hashCode ^
      artist.hashCode ^
      chapters.hashCode ^
      images.hashCode ^
      stylesheets.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EpubNovel &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          cover == other.cover &&
          summary == other.summary &&
          author == other.author &&
          artist == other.artist &&
          chapters == other.chapters &&
          images == other.images &&
          stylesheets == other.stylesheets;
}

class EpubResource {
  final String name;
  final Uint8List content;

  const EpubResource({required this.name, required this.content});

  @override
  int get hashCode => name.hashCode ^ content.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EpubResource &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          content == other.content;
}
