// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

class HoshiDictionaryStyle {
  final String dictName;
  final String styles;

  const HoshiDictionaryStyle({required this.dictName, required this.styles});

  @override
  int get hashCode => dictName.hashCode ^ styles.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HoshiDictionaryStyle &&
          runtimeType == other.runtimeType &&
          dictName == other.dictName &&
          styles == other.styles;
}

class HoshiFrequency {
  final int value;
  final String displayValue;

  const HoshiFrequency({required this.value, required this.displayValue});

  @override
  int get hashCode => value.hashCode ^ displayValue.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HoshiFrequency &&
          runtimeType == other.runtimeType &&
          value == other.value &&
          displayValue == other.displayValue;
}

class HoshiFrequencyEntry {
  final String dictName;
  final List<HoshiFrequency> frequencies;

  const HoshiFrequencyEntry({
    required this.dictName,
    required this.frequencies,
  });

  @override
  int get hashCode => dictName.hashCode ^ frequencies.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HoshiFrequencyEntry &&
          runtimeType == other.runtimeType &&
          dictName == other.dictName &&
          frequencies == other.frequencies;
}

class HoshiGlossaryEntry {
  final String dictName;
  final String glossary;
  final String definitionTags;
  final String termTags;

  const HoshiGlossaryEntry({
    required this.dictName,
    required this.glossary,
    required this.definitionTags,
    required this.termTags,
  });

  @override
  int get hashCode =>
      dictName.hashCode ^
      glossary.hashCode ^
      definitionTags.hashCode ^
      termTags.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HoshiGlossaryEntry &&
          runtimeType == other.runtimeType &&
          dictName == other.dictName &&
          glossary == other.glossary &&
          definitionTags == other.definitionTags &&
          termTags == other.termTags;
}

class HoshiImportResult {
  final bool success;
  final String title;
  final BigInt termCount;
  final BigInt metaCount;
  final BigInt freqCount;
  final BigInt pitchCount;
  final BigInt mediaCount;
  final List<String> errors;

  const HoshiImportResult({
    required this.success,
    required this.title,
    required this.termCount,
    required this.metaCount,
    required this.freqCount,
    required this.pitchCount,
    required this.mediaCount,
    required this.errors,
  });

  @override
  int get hashCode =>
      success.hashCode ^
      title.hashCode ^
      termCount.hashCode ^
      metaCount.hashCode ^
      freqCount.hashCode ^
      pitchCount.hashCode ^
      mediaCount.hashCode ^
      errors.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HoshiImportResult &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          title == other.title &&
          termCount == other.termCount &&
          metaCount == other.metaCount &&
          freqCount == other.freqCount &&
          pitchCount == other.pitchCount &&
          mediaCount == other.mediaCount &&
          errors == other.errors;
}

class HoshiLookupResult {
  final String matched;
  final String deinflected;
  final List<HoshiTransformGroup> trace;
  final int preprocessorSteps;
  final HoshiTermResult term;

  const HoshiLookupResult({
    required this.matched,
    required this.deinflected,
    required this.trace,
    required this.preprocessorSteps,
    required this.term,
  });

  @override
  int get hashCode =>
      matched.hashCode ^
      deinflected.hashCode ^
      trace.hashCode ^
      preprocessorSteps.hashCode ^
      term.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HoshiLookupResult &&
          runtimeType == other.runtimeType &&
          matched == other.matched &&
          deinflected == other.deinflected &&
          trace == other.trace &&
          preprocessorSteps == other.preprocessorSteps &&
          term == other.term;
}

class HoshiPitchEntry {
  final String dictName;
  final Int32List pitchPositions;
  final List<String> transcriptions;

  const HoshiPitchEntry({
    required this.dictName,
    required this.pitchPositions,
    required this.transcriptions,
  });

  @override
  int get hashCode =>
      dictName.hashCode ^ pitchPositions.hashCode ^ transcriptions.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HoshiPitchEntry &&
          runtimeType == other.runtimeType &&
          dictName == other.dictName &&
          pitchPositions == other.pitchPositions &&
          transcriptions == other.transcriptions;
}

class HoshiTermResult {
  final String expression;
  final String reading;
  final String rules;
  final int score;
  final List<HoshiGlossaryEntry> glossaries;
  final List<HoshiFrequencyEntry> frequencies;
  final List<HoshiPitchEntry> pitches;

  const HoshiTermResult({
    required this.expression,
    required this.reading,
    required this.rules,
    required this.score,
    required this.glossaries,
    required this.frequencies,
    required this.pitches,
  });

  @override
  int get hashCode =>
      expression.hashCode ^
      reading.hashCode ^
      rules.hashCode ^
      score.hashCode ^
      glossaries.hashCode ^
      frequencies.hashCode ^
      pitches.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HoshiTermResult &&
          runtimeType == other.runtimeType &&
          expression == other.expression &&
          reading == other.reading &&
          rules == other.rules &&
          score == other.score &&
          glossaries == other.glossaries &&
          frequencies == other.frequencies &&
          pitches == other.pitches;
}

class HoshiTransformGroup {
  final String name;
  final String description;

  const HoshiTransformGroup({required this.name, required this.description});

  @override
  int get hashCode => name.hashCode ^ description.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HoshiTransformGroup &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          description == other.description;
}
