// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

Future<List<RarEntry>> listRarEntries({required String archivePath}) =>
    RustLib.instance.api.crateApiRarListRarEntries(archivePath: archivePath);

Future<List<RarEntryData>> extractRarEntries({required String archivePath, required List<String> entryNames}) =>
    RustLib.instance.api.crateApiRarExtractRarEntries(archivePath: archivePath, entryNames: entryNames);

class RarEntry {
  final String name;
  final bool isFile;

  const RarEntry({required this.name, required this.isFile});

  @override
  int get hashCode => name.hashCode ^ isFile.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RarEntry && runtimeType == other.runtimeType && name == other.name && isFile == other.isFile;
}

class RarEntryData {
  final String name;
  final Uint8List content;

  const RarEntryData({required this.name, required this.content});

  @override
  int get hashCode => name.hashCode ^ content.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RarEntryData && runtimeType == other.runtimeType && name == other.name && content == other.content;
}
